language: python
os:
  - linux
python:
  - '3.7.6'
before_install:
  # Example from https://github.com/astrofrog/example-travis-conda/
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash ./miniconda.sh -b
  - export PATH=~/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - conda env create -f environment.yml
  - source activate suite2p
  - pip install --upgrade --force-reinstall pycparser  # https://github.com/eliben/pycparser/issues/251
  - python setup.py install
script:
  - python setup.py test


