name: suite2p-dev
dependencies:
  - python>=3.7,<3.8
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-learn
  - pyqt
  - pyqtgraph
  - natsort
  - pip:
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader
    - pytest>=5.4
    # '--editable .' Installs suite2p from the local directory in editable mode (i.e. setup.py develop)
    - '--editable .'
